# Basic
title: Junion
subtitle: One more thing.
description: Hello，World! 
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
# description: Vno Jekyll is a port of my Ghost theme vno.
# creator: <a href="http://onev.cat">@onevcat</a>

url: "https://sunjunzhou.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问我的博客

# Navigation buttons in the front page.
nav:
    - {title: 简书, description: Code_Ninja, url: 'https://www.jianshu.com/u/9317e1c44003'}
    - {title: 关于我, description: about me, url: 'https://sunjunzhou.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: 3224312284
    github: sunjunzhou
    mail: www.sunjunzhou@foxmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
